apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-microproject-deployment
spec:
  selector:
    matchLabels:
      app: microproject
  replicas: 1
  template:
    metadata:
      labels:
        app: microproject
    spec:
      containers:
        - name: microprojectcontainer
          image: hizokai/k8s-microproject
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: the-map
          volumeMounts:
          - name: k8s-microproject-persistent-storage
            mountPath: /usr/share/nginx/html
      volumes:
      - name: k8s-microproject-persistent-storage
        persistentVolumeClaim:
          claimName: my-pvc

    
